---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout=100 

    - name: "install python for Ansible."
      become: yes
      apt:
        name: "python3"
        state: latest
        update_cache: yes 

  
  environment:
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: /home/ubuntu/src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST:  database-1.cfhorryrv8tp.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: Nandhubabu11
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: /home/ubuntu/src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: /home/ubuntu/src/migrations

  roles:
    - configure-server