---
- name: creating a destination folder
  file:
    path: /home/ubuntu/webapp
    state: directory

- name: creating a destination folder
  file:
    path: /home/ubuntu/dist
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "extract zipped artifact into ec2 instance"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
  
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm", "net-tools", "curl"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "installing pm2 in home folder"
  become: yes
  become_user: root  
  shell: |
      cd /home/ubuntu/
      npm install pm2 -g

- name: "Start the app"
  become: yes
  become_user: root  
  shell: | 
      cd /home/ubuntu/dist

      pm2 list 
      pm2 stop default 
      pm2 start main.js --name backend -f 
 
      netstat -tulpn | grep LISTEN
      curl localhost:3030/api/status
    
  

