---
- name: creating a destination folder
  file:
    path: /home/ubuntu/webapp
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "extract zipped artifact into ec2 instance"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
  
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    
- name: "start the application"
  become: true

  environment:
    - NODE_ENV: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: /home/ubuntu/src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST:  database-1.cfhorryrv8tp.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: Nandhubabu11
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: /home/ubuntu/src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: /home/ubuntu/src/migrations

  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm i
    npm run build
    
    /usr/local/bin/pm2 start /home/ubuntu/dist/main.js --name backend -f

  

