---
- name: creating a destination folder
  file:
    path: /home/ubuntu/webapp
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/webapp

- name: "extract zipped artifact into ec2 instance"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/webapp
  
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "start the app"
  become: yes
  shell: |
      cd ./dist
      pm2 stop default
      pm2 start npm -- start
