---
- name: creating a destination folder
  file:
    path: /home/ubuntu/webapp
    state: directory

- name: creating a destination folder
  file:
    path: /home/ubuntu/dist
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "extract zipped artifact into ec2 instance"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
  
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm", "net-tools"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "installing pm2 in home folder"
  become: yes
  shell: |
      cd /home/ubuntu/
      npm install pm2 -g
    
- name: "start the application"
  become: true

  environment:
    - NODE_ENV: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST:  database-1.cfhorryrv8tp.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: Nandhubabu11
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations

  shell: |
    cd /home/ubuntu/dist
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm i
    npm run build
    pm2 stop default
    pm2 start main.js --name backend -f

    pm2 status all
    netstat -tulpn | grep LISTEN
    curl localhost:3030/api/status

  

