---
- name: creating a destination folder
  file:
    path: /home/ubuntu/webapp
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "extract zipped artifact into ec2 instance"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/
  
- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/dist
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm install -g pm2
    pm2 start main.js 